name: Release

on:
  push:
    branches: [ master, github-actions ]
    tags:
      - "*.*.*"
  pull_request:
    branches: [ master, github-actions ]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.3

    - uses: actions/checkout@v2
    - name: Build
      run: CGO_ENABLED=0 cd p2pd && go build .

    - name: Compress binaries
    - uses: svenstaro/upx-action@v2
      with:
        file: p2pd/p2pd

    - name: Publish To Releases
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/mything
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
